### PR TITLE
Updating last_used_at on every token usage

### PR DESCRIPTION
**Pull request by bruno-campos**
Fix https://github.com/adamniedzielski/tiddle/issues/56

Removed the check to update last_activity_at only if token last_activity_at was greater than 1 hour ago.

### CODE REVIEW

**Comment by alejandrodevs** [comment]
@bruno-campos This will hit the db once more every request. I understand that this is the expected behavior but I think we should find a better way to achieve it. Maybe we can use a config to tell tiddle how ofter it should touch the token. What do you think?

**Comment by bruno-campos** [comment]
@alejandrodevs that looks great as well!

**Comment by bruno-campos** [comment]
Also added a config `touch_token_interval` following Alejandro suggestion. I can happily change the config name in case a better one comes in.

**Comment by alejandrodevs** [comment]
@bruno-campos I really like this approach! This can help us in future configuration options. @adamniedzielski What do you think?

**Comment by adamniedzielski** [comment]
I wonder if there's a way to fix the bug described in #56 without introducing a configuration option 🤔 

1. One of the goals of Tiddle (described at the top of README) is "Tiddle is lightweight and non-configurable." 😄 
2. The bug still exists if you set `touch_token_interval` to `1.hour` and `expires_in` to `30.minutes`. There's an implicit dependency between these two values which is hard to see for a new user of the gem.

What if we changed the logic from:

"touch the token if it was last used more than an hour ago"

to:

"touch the token if it was last used more than X ago, where X is the minimum of two hours and the `expires_in` of the token, divided by two"

?

Examples:
1. `expires_in` equal to 24 hours. Minimum of [2 hours, 24 hours] is 2 hours. Divide by 2 and we have 1 hour.
2. `expires_in` is not set. Minimum of [2 hours, infinity] is 2 hours. Divide by 2 and we have 1 hour.
3. `expires_in` is set to 30 minutes. Minimum of [2 hours, 30 minutes] is 30 minutes. Divide by 2 and we have 15 minutes.

What do you think? Am I missing something here?

**Comment by bruno-campos** [comment]
Hum, that would present issues, especially for tokens with a lower expiration time, like 30 minutes. Say the user creates a token, and use it 14 minutes after. The token would expire 16 minutes after its last usage.

I can't think of a solution without letting the user have control over how often the token last_used_at should be updated.

Maybe we can have some presets? Like (values are just examples):
- expiration in more than 24 hours, update every hour
- expiration in less than 24 hours, update every 30 minutes
- expiration in less than 2 hours, update every 2 minutes
- expiration in less than 1 hour, update every minute

That does not seem ideal as well, but IMO would be better than just dividing by two because lower expiration time tokens would be able to have more up to date values.

**Comment by alejandrodevs** [comment]
@bruno-campos I like that idea! It would be transparent for developers and it would work as expected. Even that, I would keep the config, I know we want to have a very simple and non-configurable gem, but I think this will be optional.

**Comment by mattrothstein** [comment]
@alejandrodevs @bruno-campos @adamniedzielski Is there still interest in having this functionality. I am currently using Tiddle but need to update the `last_used_at` field with every request as our sessions are very restrictive. Session ends after 5 minutes of inactivity.

**Comment by alejandrodevs** [comment]
I'm still interested in having this. After this discussion, I would prefer to have the configuration approach that @bruno-campos did because otherwise we will have unexpected behaviors.

**Pull request closed without merging**
